language: go

go:
  - 1.6
  - 1.7

cache:
  directories:
    - bower_components
    - node_modules

before_install:
  - nvm --version
  - nvm install 7.2.0
  - node --version && npm --version

install:
  - go get -u github.com/stretchr/testify
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -v github.com/kardianos/govendor
  - govendor sync -v
  - npm install -g yarn
  - yarn install

script:
  - go build
  - travis_wait 30 gometalinter --vendor --deadline=10m --config=./gometalinter.json ./server/... ./model/... ./cmd/... .
  - go test ./cmd/... ./model/... ./server/...

  - npm run lint
  - npm run dist
